name: "Chromatic UI"
on:
  pull_request:
    types: [opened, reopened, synchronize, reopened]
    branches:
      - main
    paths:
      - "packages/ui/**"
  push:
    branches:
      - main
    path:
      - "packages/ui/**"
jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install dependencies
        # ⚠️ See your package manager's documentation for the correct command to install dependencies in a CI environment.
        run: npm ci
      - name: Run UI Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_UI }}
          onlyChanged: true
          exitZeroOnChanges: true
          workingDir: packages/ui
  force-success:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Set multiple status checks to success
        run: |
          checks=("UI Review: APP" "UI Test: APP")
          
          for check in "${checks[@]}"; do
            curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github+json" \
                 https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
                 -d "{
                   \"state\": \"success\",
                   \"context\": \"$check\",
                   \"description\": \"Manually marked as successful\"
                 }"
          done
  check-status-success:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Set multiple status checks to success
        run: |
            curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github+json" \
                 https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
                 